on:
  push:
  pull_request:

name: Build
jobs:
  build-cli:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        package-set: ["", pkgsCross.aarch64-multiplatform., pkgsCross.armv7l-hf-multiplatform., pkgsCross.gnu32.]

    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v26
      - uses: DeterminateSystems/magic-nix-cache-action@v4
        with:
          diagnostic-endpoint: ""

      - run: echo "CARGO_BUILD_TARGET=$(nix eval --raw nixpkgs/20f77aa09916374aa3141cbc605c955626762c9a#${{ matrix.package-set }}pkgsStatic.stdenv.targetPlatform.rust.rustcTargetSpec)" >> $GITHUB_ENV
      - run: echo "TARGET_PREFIX=$(nix eval --raw nixpkgs/20f77aa09916374aa3141cbc605c955626762c9a#${{ matrix.package-set }}pkgsStatic.stdenv.cc.targetPrefix)" >> $GITHUB_ENV

      # Install appropriate rust toolchain and linker
      - run: nix profile install nixpkgs/20f77aa09916374aa3141cbc605c955626762c9a#${{ matrix.package-set }}pkgsStatic.{stdenv.cc,buildPackages.cargo}

      # Make sure rust can find the linker
      - run: mkdir .cargo
      - run: |
          cat << EOF > .cargo/config
          [target."$CARGO_BUILD_TARGET"]
          linker = "${TARGET_PREFIX}cc"
          rustflags = [ "-C", "target-feature=+crt-static" ]
          EOF

      # Build
      - run: cargo build --bin hlcc-cli --release
      - run: ${TARGET_PREFIX}strip target/${{ env.CARGO_BUILD_TARGET }}/release/hlcc-cli

      - uses: actions/upload-artifact@v3
        with:
          name: hlcc-cli-${{ env.CARGO_BUILD_TARGET }}
          path: target/${{ env.CARGO_BUILD_TARGET }}/release/hlcc-cli

  build-web:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v26
      - uses: DeterminateSystems/magic-nix-cache-action@v4
        with:
          diagnostic-endpoint: ""

      - run: nix profile install nixpkgs#rustup nixpkgs#wasm-pack nixpkgs#nodejs
      - run: rustup install stable
      - run: wasm-pack build
        working-directory: hlcc-web
      - run: npm ci
        working-directory: hlcc-web/www
      - run: npx webpack
        working-directory: hlcc-web/www

      - uses: actions/upload-artifact@v3
        with:
          name: hlcc-web
          path: hlcc-web/www/dist
